on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp:
          - 24.3.3
        build_type:
          - RelWithDebInfo
        logging:
          - false
        arch:
          - x86_64
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: gleam-lang/setup-erlang@v1.1.2
      with:
        otp-version: ${{ matrix.otp }}

    - name: Run cover
      run: |
        sudo apt-get install lcov
        make cover

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
